### ISSUE TITLE
Issues trying to implement MidiJack to Unity (bolt)

### ISSUE THREAD

**Issue by FonixVR** [keijiro/unity-midi-input#1]
Hey! I've been trying to use your plugin to create a tool (MidiJack) that shows what drums are being hit but for the life of me I've been highly unsuccessful. MIDIJack works well on keyboards but not on drumsets. The signal is just too quick for MidiJack to register, that and signal is constantly flowing. I've tried to use Bolt to create the app but that is looking to not work. 

What I am trying to do is when Snare (Channel 11 Number 34) is hit then a gray circle will then change to yellow and fade back to gray until retriggered, similar to how [mrgregles's ](twitch.tv/Mrgregles) drum key works. Can you help at all?

I've been trying to figure out the code and see if I can make it not "draw" the squares like the example does

Also, it is very difficult to understand what the MidiJack is using as a channel. I had no idea what the numbers meant and someone told me it was possibly Hex numbers

**Comment by keijiro** [comment]
This is not the MidiJack repository. Please repost it to the correct repository.
